baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Technical Notes'
theme = 'notes'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Notes'
pageRef = '/notes'
weight = 20

[[menus.main]]
name = 'Manpages'
pageRef = '/man'
weight = 30

[[menus.main]]
name = 'Search'
pageRef = '/search'
weight = 40

[markup]
    [markup.highlight]
        noClasses = false